# Generated by Django 4.1.4 on 2022-12-29 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_Area')),
                ('name', models.CharField(max_length=50, verbose_name='Name_Area')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date_Area')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_Department')),
                ('name', models.CharField(max_length=55, verbose_name='Name_Department')),
                ('description', models.TextField(verbose_name='Description')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='AreaID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID_Employee')),
                ('name', models.CharField(max_length=50, verbose_name='Name_Employee')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last_Name_Employee')),
                ('occupation', models.TextField(verbose_name='Occupation_Employee')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date_Employee')),
                ('avatar', models.ImageField(upload_to='employees', verbose_name='Avatar_Employee')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='DepartmentID')),
            ],
        ),
    ]
